# circleCIのバージョン指定
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
# Djangoのテストを実行
      - checkout
      # - run:
      #     name: docker-compose up
      #     command: docker-compose up -d --build
      # - run:
      #     name: sleep for launch db to migrate at Django
      #     command: sleep 10
      # - run:
      #     name: migrate
      #     command: docker-compose exec go bash
      # - run:
      #     name: test
      #     command: docker-compose run python ./manage.py test
      # # - run:
      #     name: docker-compose down
      #     command: docker-compose down
# EC2にSSH接続し、デプロイを実行
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      # CircleCIに登録した秘密鍵を呼び出す。
      - add_ssh_keys:
        # fingerprints: 
        #   - "b5:68:12:84:d4:b2:5d:d6:21:0c:0d:45:6c:dd:ee:43"
      - run: ssh ${USER_NAME}@${HOST_NAME}  "cd app/mysqlgo && git pull "
      # - run: git pull && docker-compose up -d --build && docker-compose exec go bash && go run docker/go/main.go"
      # - run: cd app/mysqlgp

#'cd app/mysqlgo && git pull && docker-compose up -d --build && docker exec go bash && go run docker'
# テストが成功した場合のみ、deployを実行するようにします。
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # mainブランチがpushされた場合のみdeployするようにする。
          filters:
            branches:
              only: main